import decman
import decman.config

# List of ignored packages to stop decman removing them
decman.ignored_packages += ["yay", "yay-debug", "decman", "grantlee"]

decman.packages += [
    'base', 
    'base-devel', 
    'bat', 
    'brightnessctl', 
    'devtools', 
    'dunst', 
    'efibootmgr', 
    'fastfetch', 
    'firefox', 
    'git', 
    'gnome-keyring', 
    'go', 
    'grub', 
    'hyprcursor', 
    'hypridle', 
    'hyprland', 
    'hyprlock', 
    'ttf-jetbrains-mono-nerd',
    'ttf-nerd-fonts-symbols-common',
    'ttf-nerd-fonts-symbols-mono',
    'jq', 
    'kitty', 
    'less', 
    'libnotify', 
    'lightdm',
    'lightdm-gtk-greeter',
    'linux', 
    'linux-firmware', 
    'make', 
    'neovim', 
    'networkmanager', 
    'network-manager-applet', 
    'nmap', 
    'obsidian', 
    'openbsd-netcat', 
    'os-prober', 
    'pavucontrol', 
    'python', 
    'python-pip', 
    'rofi', 
    'stow', 
    'sudo', 
    'swww', 
    'thunar', 
    'tmux', 
    'tree', 
    'unzip', 
    'uv', 
    'uwsm', 
    'waybar', 
    'wget', 
    'zsh'
]
